// lib/components/VtTableCell.jsx
import RLTableCell from "./renderless/RLTableCell";

export default {
    name: 'VtTableCell',
    props: ['column'],
    components: { RLTableCell },
    render() {
        return <r-l-table-cell column={this.column} scopedSlots={
            {
                default: (props) => {
                    return props.override ? h(props.override, {attrs:{props}}) : <td tabindex="0">
                        {props.content}
                    </td>
                }
            }
        }
        >
        </r-l-table-cell>
    }
}

// templates/VtTableCell.vue
<template>
    <td tabindex="0" :class="props.classes">
        <vnodes :vnodes="props.content"/>
    </td>
</template>

<script>
    export default {
        name: "VtTableCell",
        props: ['props'],
        components: {
            vnodes: {
                functional: true,
                render: (h, ctx) => typeof ctx.props.vnodes === 'object' ? ctx.props.vnodes : [ctx.props.vnodes]
            }
        }
    }
</script>

<style scoped>

</style>
